#!/bin/sh
#
# @name GLDrone
#
# @type Quadrotor x
# @class Copter
#
# @board px4_fmu-v2 exclude
# @board px4_fmu-v3 exclude
# @board px4_fmu-v4 exclude
# @board px4_fmu-v4pro exclude
# @board px4_fmu-v5 exclude
# @board px4_fmu-v5x exclude
#
. ${R}etc/init.d/rc.mc_defaults

# param set-default CBRK_SUPPLY_CHK 894281
# param set-default CBRK_USB_CHK 197848

# param set-default IMU_GYRO_CUTOFF 100
# param set-default IMU_ACCEL_CUTOFF 30

param set-default SYS_HAS_MAG 0
param set-default EKF2_AID_MASK 2
param set-default EKF2_MAG_TYPE 5

param set-default PWM_MAIN_DISARM 0
param set-default PWM_MAIN_MIN 5000
param set-default PWM_MAIN_MAX 65535
param set-default PWM_MAIN_RATE 80000

